### ISSUE TITLE
Doesn't split final sentence 

### ISSUE THREAD

**Issue by lexibirch** [emjotde/eserix#2]
Hi there,

I have found a strange behaviour while debugging the SUMMA MT module. Eserix depends on capitalization being correct. Is this a bug? Example below. This is a problem because we do not have correct capitalisation in ASR output. But we could get the punctuation module to uppercase all words following an inserted full stop and leave eserix alone. 

abmayne@sif:~/experiments/summa/hackathon17/summa-mt$ /mnt/skaol0/lexi/experiments/summa/hackathon17/summa-mt/eserix/build/bin/eserix -r /mnt/skaol0/lexi/experiments/summa/hackathon17/summa-mt/eserix/srx/rules.srx -l de -t  
(INPUT) this is a test with a long sentence . And another test . He He he . this is a
(OUTPUT - correct) this is a test with a long sentence .
(OUTPUT - correct) And another test .
(OUTPUT - incorrect) He He he . this is a

(INPUT) this is a test with a long sentence . And another test . He He he . This is a
(OUTPUT - correct) this is a test with a long sentence .
(OUTPUT - correct) And another test .
(OUTPUT - correct) He He he . 
(OUTPUT - correct) This is a

**Comment by emjotde** [comment]
Hi,
this is a very simple regular expression-driven tool. I think most rules do indeed expect proper capitalization.

**Comment by lexibirch** [comment]
ok thanks
